### ISSUE TITLE
Update desktop and vdi's to link to each other

### ISSUE THREAD

**Issue by ericfranz** [OSC/osc-ood-config#33]
In the description of the desktop apps, add something like:

```
If you resource needs are small and can work with one core on a shared node [use VDI instead for shorter queue times](/pun/sys/dashboard/batch_connect/sys/bc_desktop/vdi-owens/session_contexts/new).
```

In description of VDI apps, add something like "If you need more resources than one core on a shared node..." and link to the corresponding desktop app.

Changes to form.yml files under https://github.com/OSC/osc-ood-config/tree/master/ondemand.osc.edu/apps/bc_desktop and duplicated at https://github.com/OSC/osc-ood-config/tree/master/apps.awesim.org/apps/bc_desktop

I think a rake task runs a test to verify the two are in sync, so you could edit one, run the rake task, and it will complain until you make them similar.

The descriptions handle markdown, so that is all that is needed here.

To test: clone osc-ood-config, then install the dashboard in your dev directory, and add a .env file to the dashboard to set OOD_BC_APP_CONFIG_ROOT to the apps directory of awesim or ondemand in the osc-ood-config clone.

**Comment by johrstrom** [comment]
Got your comments about being concise. Trying to setup the apps in my env at the moment. Only seem to get owens and pitzer and only desktop, not VDI.  Verbiage aside - I want to be sure the redirects work correctly.

**Comment by ericfranz** [comment]
This is code complete. Marking as closed.
