### ISSUE TITLE
Reword VDI descriptions

### ISSUE THREAD

**Issue by johrstrom** [OSC/osc-ood-config#49]
The current description VDIs as `an interactive desktop with one core which could be shared.` seems to have caused some confusion, specifically around sharing. 

This task is to create a description that is perhaps more verbose and more in line with what is on the OSC website.  Given here below:

`The Virtual Desktop Interfaces should not be used for computationally or memory intensive processes because it is a shared resource and there are other users on the same node. Such processes will be terminated. Please peform such work on compute node as discussed below.`

**Comment by treydock** [comment]
We use cgroups so resource intensive is fine, they can't impact other users, just themselves if they request too few resources. I think VDI is for short interactive work.

**Comment by johrstrom** [comment]
To be clear, the wording in the description is copied from the [osc.edu documentation](https://www.osc.edu/resources/online_portals/ondemand) in the 'Virtual Desktop Interface' dropdown.
